"""Validate files generated by the installed artifact dispatcher with independent readers."""
import json
import sys
from pathlib import Path
from docx import Document
from openpyxl import load_workbook
from pptx import Presentation
from pypdf import PdfReader
import pypdfium2 as pdfium

report_path = Path(sys.argv[1]).resolve()
report = json.loads(report_path.read_text(encoding="utf-8-sig"))
assert report["status"] == "complete", report
root = Path(report["artifacts"])
doc = Document(root / "sample.docx")
assert "Hola, María." in [p.text for p in doc.paragraphs]
book = load_workbook(root / "sample.xlsx", data_only=False)
sheet = book["Gastos"]
assert sheet["B2"].value == 30 and sheet["B2"].data_type == "n"
assert sheet["A3"].value == "=NO_EJECUTAR()" and sheet["A3"].data_type == "s"
assert sheet["B3"].value is True
deck = Presentation(root / "sample.pptx")
texts = [shape.text for shape in deck.slides[0].shapes if shape.has_text_frame]
assert len(deck.slides) == 1 and "Hola, Kuky" in texts
pdf = PdfReader(root / "sample.pdf", strict=True)
assert "Hola, María." in pdf.pages[0].extract_text()
with pdfium.PdfDocument(root / "sample.pdf") as document:
    image = document[0].render(scale=1.25).to_pil()
    image.save(root / "pdf-preview.png")
result = {"status": "complete", "scope": "Independent OOXML readers, PDF parser and PDF rasterization; no AI inference.",
          "checks": ["DOCX paragraphs", "XLSX numeric, boolean and literal = text", "PPTX slide and text shapes", "strict PDF xref/text", "PDF raster preview"],
          "preview": str(root / "pdf-preview.png")}
report_path.with_name("artifact-readers.json").write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
print(json.dumps(result, ensure_ascii=False))
